[package]
name = "week_05_2"
version = "0.1.0"
authors = ["Stuart Haidon <serayen.sh@gmail.com>"]

[dependencies]
tcod-sys = "4.0.1"
tcod = "0.11.0"
num = "0.1.39"
rand = "0.3.15"
serde = "1.0.10"
serde_derive = "1.0.10"
serde_yaml = "0.7.1"
textwrap = "0.7.0"